export const SELECT_EXCHANGE = "SELECT_EXCHANGE"
export const ADD_MY_EXCHANGE = "ADD_MY_EXCHANGE"
export const DELETE_MY_EXCHANGE = "DELETE_MY_EXCHANGE"
export const GET_EXCHANGES_DATA = "GET_EXCHANGES_DATA"